name: Trigger Workflow in Repository B

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Repository B
        env:
          TOKEN: ${{ secrets.REPO2_DISPATCH_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -d '{"event_type": "workflow-trigger", "client_payload": {"key": "value"}}' \
            https://api.github.com/repos/arpitjindal-pythonD/azure-arc-webapp/dispatches
